name: build

on:
  push:
    branches:
      - 'test'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup Go env
        uses: actions/setup-go@v2.1.3

      - name: Build Go binary
        run : |
          go get github.com/jteeuwen/go-bindata/...
          /home/runner/go/bin/go-bindata -o check.go check.sh
          GOOS=linux GOARCH=386 go build -o artifact/RegionRestrictionCheck_386
          GOOS=linux GOARCH=amd64 go build -o artifact/RegionRestrictionCheck_amd64
          GOOS=linux GOARCH=arm64 go build -o artifact/RegionRestrictionCheck_arm64
          GOOS=linux GOARCH=ppc64le go build -o artifact/RegionRestrictionCheck_ppc64le
          GOOS=linux GOARCH=arm go build -o artifact/RegionRestrictionCheck_arm

      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          name: RegionRestrictionCheck
          allowUpdates: true
          commit: test
          replacesArtifacts: true
          token: ${{ secrets.GH_TOKEN }}
          tag: v1.0
          artifacts: ./artifact/RegionRestrictionCheck*

      - name: Build images
        run: |
          sed -i '2i Hulu_Cookie="${{ secrets.HULU_COOKIES }}"' check.sh
          docker buildx build --output "type=image,push=true" --platform=linux/ppc64le,linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386 --tag ${{ github.repository_owner }}/regioncheck:go .
